name: testproject
description: A movie rental app built with Flutter.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # video player
  video_player: ^2.7.0
  youtube_player_flutter: ^8.1.1
  # fire store
  firebase_core: ^2.25.0
  # cloud storage
  cloud_firestore: ^4.9.2
  # http requests
  http: ^0.13.6


flutter:
  uses-material-design: true
  assets:


flutter_assets:
  android: true
  ios: true
  web: true
  windows: true
  macos: true
  linux: true
