name: testproject
description: A movie rental app built with Flutter.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  # video player
  video_player: ^2.7.0
  youtube_player_flutter: ^8.1.1
  # http requests
  http: ^0.13.6


flutter:
  uses-material-design: true


flutter_assets:
  android: true
  ios: true
  web: true
  windows: true
  macos: true
  linux: true
